#!/bin/bash
MY_NAME=$(basename $0)
cd $(dirname $0)
MY_DIR=$PWD
cd - > /dev/null

VERSION=1.1

set -o nounset

source ~/.bash_functions

function show_usage()
{
	printf "usage: %s [options]\n" $MY_NAME
	printf "options:\n"
	printf "\t-h | --help - show this help message\n"
	printf "\t-c | --copy <device path> - copy resulting tarball to snickerdoodle@<device path> (i.e. <host>:<path>)\n"
	printf "\t-v | --version - show version and quit\n"
	printf "\t-y | --dry-run - show commands to be executed, but do not execute them\n"
}

function get_num_cpus()
{
	lscpu | grep '^CPU(s):' | cut -d':' -f2 | xargs
}

function build_kernel()
{
	local num_jobs=${1:-4}
	printf "%s: building uImage\n" $MY_NAME
	$do make -j${num_jobs} ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- LOADADDR=0x8000 uImage
}

function build_modules()
{
	local num_jobs=${1:-4}
	printf "%s: building modules\n" $MY_NAME
	$do make -j${num_jobs} ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- modules
}

function get_temp_path()
{
	echo ~/Temp/$(today)
}

function create_temp_dir()
{
	local path=${1:?}
	if [[ -e "$path" ]]
	then
		$do sudo rm -r $path/*
	fi
	$do mkdir -p $path
}

function copy_to_temp_dir()
{
	local path=${1:?}
	local num_jobs=${2:-4}
	printf "%s: gathering files\n" $MY_NAME
	$do sudo make -j${num_jobs} ARCH=arm INSTALL_MOD_PATH=$path modules_install
	$do sudo cp arch/arm/boot/uImage $path
}

function validate_temp_dir()
{
	local path=${1:?}
	local ret=0
	if [[ ! -f $path/uImage ]]
	then
		printf "%s: %s not found\n" $MY_NAME $path/uImage 1>&2
		ret=$((ret + 1))
	fi
	if [[ ! -d $path/lib ]]
	then
		printf "%s: %s not found\n" $MY_NAME $path/lib 1>&2
		ret=$((ret + 1))
	fi
	return $ret
}

function create_tarball()
{
	local path=${1:?}
	cd $path
	local tarball=$(strings uImage | grep nanotok).tar.gz
	printf "%s: creating tarball %s\n" $MY_NAME $path/$tarball
	$do sudo tar czf $tarball uImage lib
}

function copy_to_device()
{
	local path=${1:?}
	local device=${2:?}
	printf "%s: copying to %s\n" $MY_NAME $device
	$do sshpass -p snickerdoodle scp $path/Linux*-nanotok-*.tar.gz snickerdoodle@${device}
}

do=

dry_run=0
device_path=
while [[ $# -gt 0 && "$1" =~ ^- && ! "$1" == "--" ]]
do
	case $1 in
		-h | --help )
			show_usage
			exit 1
			;;
		-v | --version )
			echo "$VERSION"
			exit
			;;
		-c | --copy )
			shift
			device_path=${1:?device path required}
			;;
		-y | --dry-run )
			dry_run=1
			do=echo
			;;
		* )
			printf "%s: unknown option: \"%s\"\n" $MY_NAME $1 1>&2
			show_usage
			exit 1
			;;
	esac
	shift
done

if [[ $# -ne 0 && "$1" == '--' ]]
then
	shift
fi

num_cpus=$(get_num_cpus)
build_kernel $num_cpus && build_modules $num_cpus
result=$?
if [[ $result -ne 0 ]]
then
	printf "%s: build failed, aborting\n" $MY_NAME 1>&2
	exit 1
fi

temp_path=$(get_temp_path)
create_temp_dir $temp_path && copy_to_temp_dir $temp_path $num_cpus && validate_temp_dir $temp_path
result=$?
if [[ $dry_run -eq 0 && $result -ne 0 ]]
then
	printf "%s: failed validation, aborting\n" $MY_NAME 1>&2
	exit 1
fi

create_tarball $temp_path
result=$?
if [[ -n "$device_path" ]]
then
	if [[ $dry_run -ne 0 || $result -eq 0 ]]
	then
		copy_to_device $temp_path $device_path
	fi
fi
